const TOKEN_BOT = '6046633708:AAHTp-drqafLO-HFxybW5wNwnaz0FqSPlOY';
const API_KEY = 'a7a2ac74671f6f726e75c4196603a5ed';

const CITY_NAME = 'Tel-Aviv';
const TEXT_INTERVAL_3_HOURS = 'At intervals of 3 hours';
const TEXT_INTERVAL_6_HOURS = 'At intervals of 6 hours';
const TEXT_FORCAST = `Weather forcast in ${CITY_NAME}`;
const TEXT_EXCHANGE_RATES = 'Exchange rates';
const TEXT_PREVIOUS_MENU = 'Previous menu';

const CURRENCY_EUR = 'EUR';
const CURRENCY_USD = 'USD';
const CURRENCY_CODE_EUR = 978;
const CURRENCY_CODE_USD = 840;
const CURRENCY_CODE_UAH = 980;

module.exports = {
  API_KEY,
  TOKEN_BOT,
  CITY_NAME,
  TEXT_INTERVAL_3_HOURS,
  TEXT_INTERVAL_6_HOURS,
  TEXT_FORCAST,
  TEXT_EXCHANGE_RATES,
  TEXT_PREVIOUS_MENU,
  CURRENCY_EUR,
  CURRENCY_USD,
  CURRENCY_CODE_EUR,
  CURRENCY_CODE_USD,
  CURRENCY_CODE_UAH,
};
